import "./globals.css";
import type { Metadata } from "next";
import { Red_Hat_Text } from "next/font/google";

const redHatText = Red_Hat_Text({
  weight: ["700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Frontend Mentor | Launch countdown timer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={redHatText.className}>{children}</body>
    </html>
  );
}
